import type { Metadata } from "next";
import localFont from "next/font/local";
import "./sass/globals.scss";
import BootstrapClientJS from "./components/BootstrapClientJS/BootstrapClientJS";
import Header from "@/app/components/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header><Header /></header>
        <main>{children}</main>
        <footer>Footer</footer>
        <BootstrapClientJS />
      </body>
    </html>
  );
}
